wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1664457690.53625
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.0
      5: 0.13.3
      8:
      - 5
